name: gpoo_env
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.7.4
  - pip:
    - colorama==0.4.4
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==5.0.9
    - gpy==1.10.0
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - numpy==1.21.2
    - paramz==0.9.5
    - pillow==8.3.2
    - pretty-errors==1.2.24
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - scipy==1.7.1
    - six==1.16.0
